// <auto-generated />
namespace MHser.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fk_updateuser_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_updateuser_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201811120740585_fk_updateuser_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
