// <auto-generated />
namespace MHser.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011452440_roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
